### ISSUE TITLE
Benchmark comparison

### ISSUE THREAD

**Issue by mikeptweet** [imba/imba#131]
This is an impressive framework and the performance seems to be outstanding. Have you considered posting your framework to https://krausest.github.io/js-framework-benchmark/current.html so that we can do an apples to apples comparison?

**Comment by leeoniya** [comment]
>  These elements are compiled to an inline dom, which is an order of magnitude faster than todays virtual dom implementations.

this claim is demonstrably false.

according to your bench on my PC, imba claims to be 22.26x faster than React, which is literally impossible. React is 1.79x slower than the fastest theoretically-possible implementation.

i encourage you guys to submit an implementation for some objective metrics :)

**Comment by somebee** [comment]
@leeoniya: The fastest theoretically possible implementation of what? To be honest, I would posit that the memoization technique is close to the optimally efficient way of applying changes to a DOM.
 I can guarantee that it is possible, but you must understand what we are testing; we are deliberately testing the _DOM reconciler_, without using hand-coded optimizations or complex state management frameworks.

The point is exactly that the core DOM reconciliation method of a memoized DOM is so much faster that you can do without these types of optimizations. And yes, it is that much faster. That does not mean that your app written in React + mobx would be 20 times slower, not at all. Just that you(+mobx) would be doing a lot of complex things to help the virtual dom do as little work as possible. You could help Imba the same way, but you don't need to. And that opens up for interesting possibilities.

[This article](https://codeburst.io/faster-web-c6823830ce72) by @foxbunny explains the benefits pretty well.

**Comment by leeoniya** [comment]
imba's website wording strongly implies that imba is an order of magnitude faster in web app performance. however, if dom reconciliation is only 5% of the entire typical workload, then making that portion 20x faster is inconsequential.

either way, it would be interesting to see where imba's performance lands on a level playing field, right?

**Comment by somebee** [comment]
The website says: "Your declarative views are compiled to a memoized dom, which is an order of magnitude faster than todays virtual dom implementations." I definitely stand behind this statement.

DOM reconciliation is much more than 5% of the entire typical workload, but more importantly, we are all following complicated patterns, introducing complex dependencies, and in general being constrained by state management, which is in the end mostly there because DOM reconciliation is too slow.

Imba will still be _a lot faster_ than React (you can use the exact same optimizations). I'm not arguing that React+mobx is not fast enough in most cases. I'm arguing that with a fast enough reconciler you can start developing apps in a new way, and that it is extremely liberating.

I'm also not arguing that this is a great reason for people to throw away React. But I'd love if React took notice and started using some of these techniques, to radically improve their performance and reduce complexity.

**Comment by judofyr** [comment]
> however, if dom reconciliation is only 5% of the entire typical workload, then making that portion 20x faster is inconsequential.

Well, and this is where it becomes interesting. DOM reconciliation is not important *until it is*. For most cases reconciliation is fast enough and you wouldn't notice any difference between React, Vue, jQuery or Imba. However, once you have a bottleneck in the DOM reconciliation you're essentially forced to restructure your data and code. 

To give an example: I recently worked on a React app where it suddenly took ~200ms to render a list of ~40 items when something changed in one of them. Looking at the profiling data it turns out that rendering the list of items consistently causes a minor garbage collection. In this case I improved the performance by moving code into its own component and implementing `shouldComponentUpdate`. Even that just turned it down to ~30ms which is still far too high. The way to further improve it would be to split one component into four others (so the others are not rendered when the first one changes). They are completely related components, and the code would be more complex when it's split up, so for now I'm just living with suboptimal performance. I know that once the view becomes more complex I might be forced to restructure it again.

In Imba you would require a view that's maybe 1-2 orders of magnitude more complex before you reach the same point. This means that you can structure your code and data the way *you* want, and not so that it's convenient for the DOM reconciler to efficiently diff.

> either way, it would be interesting to see where imba's performance lands on a level playing field, right?

You can write slow applications in Imba and fast applications in React/Vue. All we're saying is that due to the performance of the memoized DOM you can write apps *differently* in Imba than you would (for an equivalent performant implementation) in React/Vue.

**Comment by leeoniya** [comment]
> All we're saying is that due to the performance of the memoized DOM you can write apps differently in Imba than you would (for an equivalent performant implementation) in React/Vue.

in this case, it would actually be quite enlightening to see what an idiomatic implementation of this common benchmark would look like.

> Well, and this is where it becomes interesting. DOM reconciliation is not important *until it is.*

i think we can all agree that 80,000 dom elements in a list of 10,000 rows would be a case when reconciliation speed is critically important, and where imba should really shine, if the claims are in fact true. `js-framework-benchmark` measures this by reading chrome's devtools timeline for both timing and memory metrics.

**Comment by judofyr** [comment]
> i think we can all agree that 80,000 dom elements in a list of 10,000 rows would be a case when reconciliation speed is critically important, and where imba should really shine, if the claims are in fact true. `js-framework-benchmark` measures this by reading chrome's devtools timeline for both timing and memory metrics.

The React implementation is implemented with `shouldComponentUpdate` (https://github.com/krausest/js-framework-benchmark/blob/e580a98862ebe4af213bae56dfbaf64277b5b98d/frameworks/keyed/react/src/main.jsx#L39) so this is testing overall performance for an optimized implementation and *not* DOM reconciliation performance. So no, Imba wouldn't be 20x faster than React in this case. If you implement the same type of "avoid re-rendering when no props have changed"-logic the Imba version will probably still be faster than React.

It should also be mentioned most benchmarks that allow these type of "skip re-rendering" will have the same performance regardless of framework. Especially once you can design the structure of your app with all the requirements known in advance (e.g: you know exactly what can change, so you make that the boundary of your components). My experience is that real-life isn't that easy and that it sucks when you need to restructure big parts of your code because everything is slow.

**Comment by leeoniya** [comment]
> so this is testing overall performance for an optimized implementation and not DOM reconciliation performance. 

at the end of the day, users don't care about DOM reconciliation performance, just like they don't care about react's scheduler; what's being measured is the end result that's experienced by users.

> It should also be mentioned most benchmarks that allow these type of "skip re-rendering" will have the same performance regardless of framework. Especially once you can design the structure of your app with all the requirements known in advance (e.g: you know exactly what can change, so you make that the boundary of your components).

yes, this is a fair point. but that just makes the case stronger for imba's architecture to show that imba is fast without any kind of special `shouldComponentUpdate`-style optimizations. in fact, the frameworks that are fastest in that table do some questionable things that break out of their idiomatic styles. we're actively trying to figure out what - if anything - can be done about it without dictating any specific styles or architectures (it's not an easy problem) [1].

nevertheless, it would be good to see more implementations on board so at least the claims are *more* apples-to-apples, though i don't think they ever truly will be.

[1] https://github.com/krausest/js-framework-benchmark/issues/430

**Comment by foxbunny** [comment]
> do some questionable things that break out of their idiomatic styles.

Hahaha, like S.js maybe?

> nevertheless, it would be good to see more implementations on board so at least the claims are more apples-to-apples, though i don't think they ever truly will be.

Think about it this way. You're one of the few that's in on the secret. Let others use React and enjoy their `shouldComponentBeMoreEnjoyable()` dance. Competition is ruthless. 🗡

**Comment by foxbunny** [comment]
@leeoniya Since this is an issue tracker, I think it's best we take it to the [chat room](https://gitter.im/somebee/imba) or something. ;)

**Comment by somebee** [comment]
@leeoniya If you look at the article I mentioned @foxbunny actually compared it to a vanilla implementation. You would never write vanilla is the way Imba compiles your views, and you'd be hard pressed to match its speed :)

I will look into adding Imba to the benchmark you mention btw, it's mostly a time issue.

**Comment by leeoniya** [comment]
TBH, i consider uibench to be a more thorough test than js-framework-benchmark, though their results tend to show largely the same outcomes, albeit with less granularity in the latter. i see you guys have a pretty old version, there so it may make sense to simply bump the dep and slightly tweak the impl if necessary.

does imba have an equivalent to "keyed" and "non-keyed" modes? or does it always operate in non-keyed mode (always recycling dom nodes)? what keyed means is that when given a model list of ["a","b","c"], there is a way to guarantee that when "b" is removed from the model/state array, the dom node associated with "b" is also literally removed, rather than a mutation that changes "b" -> "c", followed by removal of "c".

in uibench, imba impl is flagged as `DOM Recycling`, so my assumption is that it always operates in non-keyed mode? this is a really important distinction, because the reconciler can be much simpler in non-keyed, and the dom cost of removing a middle node is usually much more than slightly mutating every trailing node and chopping the tail. this is why we split js-framework-benchmark tables into two distinct groups - the perf diverges that significantly.

**Comment by somebee** [comment]
We have a keyed mode as well. You specify key using `<tag@{mykey}>` syntax. In this mode, we automatically prune memoized unmounted nodes whenever the amount of cached (unused) nodes within a list reaches a certain limit (either an absolute count, or when the ratio of unmounted/mounted nodes reach a certain level).

**Comment by leeoniya** [comment]
i'll add that if your claim is that imba is 10x faster than react without sCU optimizations, then it's maybe not *that* far fetched. and i agree tgat sCU can be quite fragile to maintain by hand. however, working with deeply-immutable state structures like https://github.com/arqex/freezer makes this task essentially automatic. it's still not as elegant as pre-compilation of templates, but much less a nightmare and retaons all the speed benefits.

**Comment by localvoid** [comment]
@somebee 

> we are deliberately testing the DOM reconciler

1. Abusing implicit recycling in Imba implementation
2. Performing DOM mutation on dirty DOM trees
3. Forcing GC during updates (in real apps it will be triggered when [browser is idle](https://v8.dev/blog/free-garbage-collection))

This benchmark is completely useless.

@leeoniya 

> i can tell you that ivi does a lot of things very very quickly despite being vdom. (it's a shame he's resorted lately to the same scummy tactics as the faster ones).

I'll submit clean implementation with the next update.

> it would be great if you could make the uibench current with the latest imba and also keyed to avoid recycling

Imba is using keyed algo in uibench. The problem is that it is using implicit recycling, so when everything should be cleaned up, it keeps everything in memory and on the next iteration just reattaching existing structure. Inferno abused similar technique to get better results in benchmarks.

**Comment by foxbunny** [comment]
> Imba is using keyed algo in uibench. The problem is that it is using implicit recycling, so when everything should be cleaned up, it keeps everything in memory and on the next iteration just reattaching existing structure. Inferno abused similar technique to get better results in benchmarks.

Imba is not doing this to "get better results in benchmarks". It's doing this because it's the right thing to do for your app. The benchmark should be considered wrong for not taking this into account.

**Comment by foxbunny** [comment]
In discussions about Imba, I swear I've seen the word "everyone" like a bazillion times in the past 24 hours alone.

**Comment by judofyr** [comment]
> there is no universe in which a keyed impl would be considered cheating - it incurs a ton more internal overhead (in multiple places) than it saves (in one or two places). it keeps the dom more deterministicly in sync, which is necessary for transitions, delayed removal, animated reordering, destroying transient dom state, etc.

Hmm. The non-keyed case of a loop in Imba is essentially identical to the keyed case where the key is the index of the loop. The same mechanism is happening: The key (aka: the index, in the non-keyed case) is used to find a memoized DOM element, and then reconciliation is applied with that DOM element. The performance of a keyed vs non-keyed implementation in Imba is more about the price of reordering elements vs. updating them, not about the internal implementation.

**Comment by localvoid** [comment]
> @leeoniya what concerns do you have with correctness, so long as the nodes are properly detached from the live dom?

If it is not reusing nodes that belong to different parents or nodes associated with different keys, than I don't think that there are any serious issues, just some footguns with unexpected internal state after unmount/mount phases because of the cache purging heuristics. It just not worth it, unless you are trying to get better numbers in synthetic benchmarks like uibench.

Just did a quick test in [this benchmark](https://somebee.github.io/dom-reconciler-bench/index.html), and I think that it doesn't reuse nodes here, probably just keeps the old ones in memory and using the simplest strategy for recycling.

**Comment by somebee** [comment]
> The performance of a keyed vs non-keyed implementation in Imba is more about the price of reordering elements vs. updating them, not about the internal implementation.

That is true @judofyr, but you should know that the logic for finding the optimal insertion/removal ordering is quite complex – especially since you wrote it 😂 That code isn't used at all for non-keyed lists.

**Comment by somebee** [comment]
> Just did a quick test in [this benchmark](https://somebee.github.io/dom-reconciler-bench/index.html), and I think that it doesn't reuse nodes here, probably just keeps the old ones in memory and using the simplest strategy for recycling.

This is the benchmark I've been discussing all along. Mind you, I remembered incorrectly - we do use keyed nodes here - just like react. I do think it was actually faster non-keyed, but again, in the real world I'd use keyed items in the list, so we did that in the benchmark as well.

I will look into the old uibench implementation when I get around to it. I agree with @localvoid that if the benchmark is supposed to be _completely_ independent runs then cached nodes should be pruned between runs. But again, if you're trying to measure the real world performance of the reconciler I still mean the best benchmark is one where very small details of an unknown state is changed between each iteration.

**Comment by leeoniya** [comment]
@localvoid

> just some footguns with unexpected internal state after unmount/mount phases

if no external/uncontrolled code touches the dom, which i think is a reasonable caveat for most libs, then i think the vast majority of remaining footguns can be confined to form inputs (e.g. validation state/styling). the surface seems small enough to me that it can be controlled during recycling from a detached cache without too great a perf impact. i dont think there is a single lib with 0 footguns.

@somebee , @judofyr 

it's pretty easy to test whether an impl & framework qualifies as keyed or non-keyed - just check the dom mutations during specific actions. we do that here [1].

in a model of [a,b,c,d,e] and a matching initial dom a keyed impl will behave like this:

- swapping `b` and `d` in the model results in `parent.insertBefore(b, e)` and `parent.insertBefore(d, c)`
- deleting `c` in the model results in `parent.removeChild(c)` or `c.remove()`
- inserting some new `f` after `c` in the model results in `parent.insertBefore(f, d)`

> I will look into the old uibench implementation when I get around to it. I agree with @localvoid that if the benchmark is supposed to be completely independent runs then cached nodes should be pruned between runs. But again, if you're trying to measure the real world performance of the reconciler I still mean the best benchmark is one where very small details of an unknown state is changed between each iteration.

yeah, this is an interesting situation. in real world apps, a detached dom cache is a legit optimization. for the bench it only "appears" to be cheating because there are many iterations that are assumed to be independent (and the iterations are done synthetically just to get to some level of statistical confidence or warm op the JIT). i guess it doesnt make the results directly comparable, but i wouldnt call this cheating at all and do think that there's a very real benefit IRL.

FWIW, js-framework-benchmark does not "suffer" from this, and imba would not benefit as much because each iteration is measured independently. at the same time, it also doesnt illustrate this benefit in actual apps.

[1] https://github.com/krausest/js-framework-benchmark/blob/master/webdriver-ts/src/isKeyed.ts

**Comment by somebee** [comment]
> it's pretty easy to test whether an impl & framework qualifies as keyed or non-keyed - just check the dom mutations during specific actions. we do that here [1].

True. You can step through iterations of the dom-reconciler benchmark (here)[https://somebee.github.io/dom-reconciler-bench/index.html], and as you will see, React and Imba has the exact same amount of dom mutations. That wouldn't happen if one was keyed and the other was not :)

**Comment by localvoid** [comment]
> @leeoniya ~~FWIW, js-framework-benchmark does not "suffer" from this, and imba would not benefit as much because each iteration is measured independently. at the same time, it also doesnt illustrate this benefit in actual apps.~~ actually, it would, the warmup of "create" would pre-cache the created dom :/

It shouldn't have the same problem, each time "create" is invoked it will create rows with unique ids. And as I understand, Imba hopefully doesn't use(implicitly) dangerous recycling techniques, so it won't reuse DOM nodes because rows will have unique ids.

And `partial update` test case should be enough to prove that they have an amazing reconciler. Even with `sCU` optimization, all vdom implementations will perform diff on at least 800 DOM elements with super low ratio of data bindings per DOM element (mostly static, 0.25).

**Comment by localvoid** [comment]
Took a quick look at the generated code by Imba and in my opinion uibench is a terrible benchmark for Imba since this benchmark focuses on dynamic lists. In real apps ratio of statically positioned elements per dynamically positioned element is significantly higher. It is really hard task to create a good benchmark and that is why I don't like all this "N times faster"/"order of magnitude faster" benchmarketing BS.

**Comment by foxbunny** [comment]
You can pick the framework/language apart all day and still not learn anything about what it's like to actually develop with it. It's one thing to just be fast. It's another when speed contributes to **how you work** with the platform. That is very hard to explain until you've actually felt it under your fingers.

**Comment by ryansolid** [comment]
I think I've sort of followed the discussion here, but is there any reason why Imba hasn't been submitted to JS Frameworks Benchmark? This isn't the first time it was suggested. (#59 ) was almost 3 years ago.  I mean we can all agree that benchmarks don't properly capture the developer experience but that is sort of beside the point.

- Is it that something Imba does that would disqualify it from consideration?
- Is it that the author is concerned that it would reflect poorly in comparison to the performance claims made here?

I mean pointing out being more performant than React is sort of like shooting fish in a barrel. 1 person, a computer, some good coffee, and a free weekend can make that claim. They'd probably still have time left over to submit it to the JS Framework Benchmark as well. Maybe the claim is sufficient, but there are atleast some people who seem interested to see how it stacks up against other like minded libraries that consider performance important.  Or even optimized vanilla(plain) JS for that matter since I'm sure I can invent a scenario where I could demonstrate a library is 1000x times faster than React but what does that even mean.

I don't doubt this package does amazing things, but comparison without baseline feels like marketing fluff. That's all good, but let's get a more tangible comparison.

**Comment by somebee** [comment]
It is obviously useful to submit it to these well known benchmarks. I'm happy if someone makes Imba implementations for them, and I will do myself, when I have the time. If you look at how little time I've been able to put into Imba over the last year or two you'd understand that doing this hasn't been priority number one :)

I will still say, as mentioned in the article, that I really do think most of them benchmark things that are not too interesting for real world scenarios, especially not for answering the question "could we render opportunistically (as often as we'd like, from root) or not?".

**Comment by somebee** [comment]
I'd also like other frameworks to submit their implementations in the dom-reconciler-benchmark though! I'd like to see anyone coming close to Imba when measuring raw reconciler performance :) [lit-html](https://github.com/Polymer/lit-html) and [rawact](https://github.com/sokra/rawact) has recently been brought to my attention, and both looks super interesting!

**Comment by leeoniya** [comment]
> especially not for answering the question "could we render opportunistically (as often as we'd like, from root) or not?".

we've kinda gone over this, too: https://github.com/krausest/js-framework-benchmark/issues/163

**Comment by localvoid** [comment]
> @somebee I'd like to see anyone coming close to Imba when measuring raw reconciler performance :)

I thought about benchmark that could actually show Imba strengths, and I think that [dbmonster](https://github.com/mathieuancelin/js-repaint-perfs) with 0 mutations and without any `sCU` optimizations should be a perfect candidate. It has such ratios: `statically positioned nodes/dynamically positioned nodes === 40` (ideal for Imba, even better than TodoMVC), `data bindings/DOM node === 0.66`

Here is a slightly modified[1] dbmonster implemented with Imba: https://gitlab.com/localvoid/imba-uibench/tree/master/src . Can you check it, I hope that I haven't done anything wrong in Imba implementation.

1. `setTimeout` replaced with `rAF` to prevent mutations on dirty DOM tree, removed all garbage from traditional dbmon implementations, css is inlined into html.

**Comment by mikeptweet** [comment]
Some really impressive #'s by the glimmer-vm 

https://github.com/somebee/dom-reconciler-bench/pull/3

**Comment by somebee** [comment]
Yeah, it's crazy impressive. Yet another hint that the virtual dom is damn inefficient. Already diving into the details to see how it's even possible, and how we can improve the performance of our compiled code. Approach is pretty similar.

**Comment by lifeart** [comment]
@somebee also you may found interesting https://github.com/eigenmethod/mol

**Comment by somebee** [comment]
@mikeptweet Turns out the glimmer-vm implementation is not reconciling synchronously. When it does, it is just slightly faster than react. Added a check for that in the benchmark now. Will also add a readme to more clearly explain what it is trying to test, and what constraints each implementation should have.

**Comment by mikeptweet** [comment]
Hey @somebee this makes the difference much more understandable. It would be interesting to see how imba measures up to glimmer with an asynchronous implementation :-)

**Comment by foxbunny** [comment]
@mikeptweet Out of curiosity, how would you measure that?

**Comment by lifeart** [comment]
Current glimmer implementation not async, all DOM updates perform in `one runloop`, but yes, as @somebee sad, where is some reasonable mismatches, because glimmer has builting state management system it `shedules rendering` in `next` runloop, not current (because in current run loop other functions can change component state or property value)

**Comment by lifeart** [comment]
`async rendering` - is when DOM operations for one render performed in few run loops / requestAnimation frame calls

**Comment by somebee** [comment]
@lifeart With async I mean that it runs in "next" runloop. When benchmark.js tries to measure it runs many steps and reconciles synchronously, which the glimmer implementation skips completely. So, glimmer will render once in a while, when benchmark.js takes a break. If we did the same with Imba (just call Imba.commit instead of forcing rendering), the benchmark is basically a no-op and would be ridiculously fast, but don't measure anything at all.

**Comment by allain** [comment]
I added an imba implementation to that benchmark. It's sitting as a pull request now.

https://github.com/krausest/js-framework-benchmark/pull/492

**Comment by ryansolid** [comment]
With the recent cleanup pull request all merged in things [look good](https://krausest.github.io/js-framework-benchmark/current.html). Imba Keyed Implementation has an average 1.33 geometric slowdown over the fastest vanilla js implementation, putting in the company of some of the fastest VDOM and Direct Dom manipulating libraries (somewhere between Inferno and LitHTML). Good stuff. 

Thanks for the submission.

**Comment by localvoid** [comment]
> @ryansolid things look good

But it should be an [order of magnitude faster than todays virtual dom implementations](http://imba.io/) :man_facepalming:

**Comment by mikeptweet** [comment]
These results are disappointing (and surprising) given the hype about Imba performance.

**Comment by zb0t** [comment]
Recreated a stencil/react fiber demo.
[Repo](https://github.com/zb0t/imba-demo)
[Demo](https://imba-perf-demo.firebaseapp.com/)
