### ISSUE TITLE
Unexpected behavior when using `html:class`

### ISSUE THREAD

**Issue by pushqrdx** [imba/imba#177]
So i was fiddling around with Imba, (quite like it) and i discovered that:- 

##### Adding `html:class` to a `<self>` tag produces double class attributes 

So This

```html
<self.column.container.is-fluid html:class='row'> 
```

Generates

```html
<div class="Main column container is-fluid" class="row">
```

Even if we remove the inline classes like so
```html
<self html:class='row'> 
```
it still generates

```html
<div class="Main" class="row">
```

##### Also i found that `html:class` will add a class attribute to a normal html tag, however it'll have no effect as classes won't be applied.

**Comment by athif23** [comment]
I think it's because this `.setNestedAttr` function that generated by Imba.
*(You can look in scrimba the generated js code, `ctrl+shift+J` to generate it)* 

Instead of `.flag` it's call this `.setNestedAttr`. I don't know what this function does but, I'm sure the class attribute doesn't applied because of this. I will look for this later to make sure.

Anyway, I think PR #175 by @shreeve be good enough to solve this. We can just pass it as an array/object instead, right?

Thanks.

**Comment by pushqrdx** [comment]
#175 Will be nice addition, Although, i don't see that as an alternative to having `html:class` or at least an ability to directly use `class` attribute in conjunction with the current concise syntax. There's some cases where using the class attribute will be beneficial as discussed earlier at gitter.

**Comment by athif23** [comment]
I just remember, you can do it like this too `<self.{"column container is-fluid row"}>`. I think it will works. Can you try it?

**Comment by pushqrdx** [comment]
@athif23 no this results in the following exception
```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('column container is-fluid row') contains HTML space characters, which are not valid in tokens.
```
