### ISSUE TITLE
'not' operator require parentheses

### ISSUE THREAD

**Issue by CassianoSF** [imba/imba#204]
As can be seen here: https://scrimba.com/c/cWQnDasR

I think is just when using methods after not operator

**Comment by CassianoSF** [comment]
https://github.com/imba/imba/blob/53503dd9181b7d48aff2a213cba6930185ab549f/src/compiler/nodes.imba#L3508

I think adding this:
```
		elif @op == 'not'
			@op = '!'
```
will solve the issue

I'm not sure how to make the pull request so I leaving to you @scanf

**Comment by scanf** [comment]
Sure, will check with @somebee on Thursday and hopefully resolve it by Saturday.

I am also planning on updating the documentation soon with more details on how to setup a development environment, running / adding tests, etc. Hopefully that will make it easier to make changes.

**Comment by scanf** [comment]
Your solution won't work because the error message is not only due to a missing negation operation but a missing paranthesis. I think this has to be fixed in the lexer.  This is actually tricker than expected since there are some edge cases where it's not clear how this keyword should behave. 



@somebee do you have some pointers on how I can go about fixing this? Ideally a cast. I have written the test and it fails. https://github.com/imba/imba/commit/e97a98636caf4db88d071b447d6d8622406f39ca

## Compiled JS output

```
$ diff /tmp/good.js /tmp/bad.js
44c44,45
< 			if (!self.condition()) {
---
> 			var v_;
> 			if (((self.setCondition(v_ = self.condition() n 1),v_)) - 1) {
```

As you can see from the above JS output the last line is producing invalid Javascript when paranthesis are not used for the condition.

## Lexer tokens

```
$ diff /tmp/good.t /tmp/bad.t
23c23
<  [DEF def] test_condition [DEF_BODY] [INDENT 1] [IF if] [UNARY not] [(] condition [)] [INDENT 1] [FALSE no] [\n]
---
>  [DEF def] test_condition [DEF_BODY] [INDENT 1] [IF if] [UNARY not] condition [INDENT 1] [FALSE no] [\n]
```

**Comment by scanf** [comment]
Looks I messed up something during testing. The purposed does work, my mad.
