### ISSUE TITLE
Imbapack vs Imba-rollup

### ISSUE THREAD

**Issue by altteo** [imba/imba#314]
As I understand Imba-rollup was consumed as Imbapack into main project. But In my particular case (Wimdows) Imba-rollup works and Imbapack doesn't.

**Comment by scanf** [comment]
No so there is no feature parity with imba-rollup and imbapack. They are seperate and imba-rollup will likely replace the wepack stuff. TBH the rollup stuff is still very lmiting comparing it to webpack but that seems to be a temporary issue. Hopefully we can expose the configuration in a better way since the current JSON configuration file we are using is not optimal and does not really enable you  rich customization options like webpack does. 



I will close this issue for now but will follow up on Windows support. It's not a huge priority so contributions are really welcome though.



Thanks.
