### ISSUE TITLE
Template Literals Embedded expressions `${}`

### ISSUE THREAD

**Issue by ericvida** [imba/imba#319]
ES6 template Literals (aka. Template strings) has it's own syntax `${}` for embedding expressions within itself.

This is the expected behavior in Javascript.
```js
let foo = "hello";
let bar = "world";
let str = `{foo} ${bar}!`;
console.log(str);

>> {foo} world!
```

But, Imba compiles template literals in a different way, so if i pass the same template string it has a different result.

```imba
let foo = "hello"
let bar = "world"
let str = `{foo} ${bar}!`
console.log str

>> hello $world!
```

That is because Imba compiles to the following javascript, instead of the js in the first example above.

```imba
let foo = "hello";
let bar = "world";
let str = ("" + foo + ` $` + bar + `!`);
console.log(str);

>> hello $world!
```
# Solution:

For template literals, it would be good if embedded expressions worked the same as in ES6 just for consistency, and so that special characters and white space do not need to be escaped with a backslash every time.

```imba
let foo = "hello"
let bar = "world"
let str = `{foo} ${bar}!`
>> {foo} world!
```
`${}`is the ES6 way, but Vue uses `{{ }}`, so that's also an option. Anyhow, **I like single curly braces {} through out the rest of imba, so using ${} would be nice if it was confined for template literals.**

```imba
let foo = "hello"
let bar = "world"
let str = `{foo} {{bar}}!`

>> {foo} world!
```

**Comment by JulienMLan** [comment]
Hey, just clarifying the problem as I see it because I do think there is a issue here but had a hard time seeing exactly what was being asked for in this issue. I think the issue here is actually independent of compatibility with ES6

 Based on my brief discussion with Eric and my interpretation of this example, it seems that the problem is just that `{}` is a pattern that we expect to see literally often in strings, particularly when working with CSS, and thus not really a good fit for denoting placeholders as it would have to be escaped regularly. Eric is proposing we align with JavaScript `${}` or just double up `{{}}` though of course aligning with ruby is also an option `#{}`, any of these options are much less likely to occur literally in a string.

**Comment by somebee** [comment]
If we are to change it I think using `${}` like ES6 is the way to go

**Comment by iamtirado** [comment]
> If we are to change it I think using `${}` like ES6 is the way to go

Would it require it to change in all of imba code, or could it be just in template literals?

**Comment by iamtirado** [comment]
@somebee will this come to v2?

**Comment by somebee** [comment]
I think it should just be template literals. I started changing it a while back, but the lexer is incredibly messy , so it is a little painful to fix. Planned for v2 though
