### ISSUE TITLE
Implicit Invocation in Imba

### ISSUE THREAD

**Issue by JulienMLan** [imba/imba#329]
### Description
The Imba v1 docs stated that:

"If you end up using object:access repeatedly in your Imba code, it is very likely because you are thinking in JavaScript. In Imba, a class should only expose information and behavior through methods."

I believe that this is a great pattern, being opinionated about enforcing this behavior is a choice ruby made, and one I had thought Imba made as well.

 However, It seems as though Imba v2 abandons Imba's commitment to objects only interacting through methods. In Imba v2 the *basic* syntax: `object.message` will actually return the function `message` instead of evaluating it-- It has returned the property associated with that `message` key on the object.

I would prefer if `object.message` invoked the message method on the object `object`

### Why
I think the current behavior facilitates a lot of the less appealing patterns in JavaScript, It allows for methods to be passed around outside of the context of the object to which they belong; which, while useful in certain meta-programming cases, should not be the behavior encouraged by Imba's syntax. 

Imba's current syntax makes it too easy to rip the method from the object and pass it around-- it makes this the default, with extra syntax required to actually send the message to the object and get a response. 

## Example
Consider the code Imba v2 code
```
class Cat
	def meow
		"meow"
		
var dog = {
	bark: "bark"
}

let cat = Cat.new()
cat.meow = dog.bark
dog.bark = cat.meow

console.log(cat.meow)
console.log(dog.bark)
------------------------------
output:
bark
bark
```
Vs. The Imba v1 code:
```
class Cat
	def meow
		"meow"
		
var dog = {
	bark: "bark"
}

let cat = Cat.new()
cat.meow = dog:bark
dog:bark = cat.meow

console.log(cat.meow)
console.log(dog:bark)
------------------------------
output:
TypeError: cat.setMeow is not a function
```
The imba v2 code results in `cat.meow` outputting "bark!" whereas the Imba v1 code raises an error, because no methos setMeow exists on the instance of the `Cat` class. It was so easy to overwrite the method on my class without really thinking about *why* I would need to do that, or if it might be something I should be trying to avoid, or what the implications of this modification to the object might be.

Once again, I believe we should be able to alter methods on objects. But it is a dangerous pattern and should be guarded against.

### Possible Implementation & Open Questions
I think a motivator for this change is that it is difficult, and confusing in Imba v1 to know when to use `:` or `.` , so the decision was made to align with JavaScript. Really though, `:` should almost never be used in Imba v1, and is only used often because people are working with JavaScript libraries (I am writing a test suite in Imba v1 and do use it occasionally since I am stubbing methods). I think It is a mistake in the long run to make sweeping changes to fundamental design decisions in Imba to leverage existing JavaScript code-- If Imba works well, predictably and, consistently, people will write code and tools in Imba.

I suggest Returning to the `:` and `.` syntax, but providing people with the resources to understand what the point of it is, and that `:` may one day be phased out. It would be helpful to differentiate between JavaScript objects and Imba objects more clearly.

### Is this something you're interested in working on?
Yes, despite many good changes in Imba v2, I work exclusively In Imba v1 right now due to a loss of commitment to the 'Rubyish' ideals in Imba v2, I would love to be involved in any changes that resulted in a more polished language that still feels like Imba v1

**Comment by somebee** [comment]
In _theory_ I do agree that the ruby-way is more elegant. Still, the removal of `:`  for accessors in imba 2 is probably the one change I'm the most happy with. The problem is that, whether we like it or not, we are compiling to js and we are interacting with that underlying layer all the time. If you write libraries and programs that never deal with the dom, location, document, external libraries, json, db adapters etc I agree that we could keep `.` for implicit invocation. But in the real world - especially web applications - you end up accessing properties directly all over the place. Just looking at the two major codebases we have now (scrimba and gitspeak), it is a shitshow of `.` and `:` mixed together. After starting to port some of this to v2 it feels much nicer and more consistent with `.` always being a raw accessor.

But seeing things like `setup()` and `str.toUpperCase()` everywhere still makes my eyes hurt, coming from ruby. As an experiment I added `!` to invoke methods without arguments, and after using it for the last two weeks I've really come to love it. `setup!` and `str.toUpperCase!` looks cleaner, is easier to type (and no need to right-arrow out of the parens).

If _everything_ was created in imba land from the beginning I would have kept it. Or, I would maybe even remove `:` and require `[:key]` as in ruby. But in the real world I do think the v2 approach is better.

As for the ease of overwriting methods etc, we can instead solve that by defaulting to freeze method properties, so that they cannot be written.

**Comment by JulienMLan** [comment]
I think that is a fair argument, and wanting to make great apps easily right away is a very understandable goal. 

But I want to note that it really doesn't have anything to do with Imba *compiling** to JavaScript, it is because you want it to be *compatible with JavaScript*. Ruby compiles to C, yet it can be quite difficult to use a C library in Ruby-- and being okay with this was I believe necessary for Ruby to become delightful, even though it meant a lot of packages needed to be written in ruby to build apps that were easy to build in C.

I would very much like to find a way to write something that compiles to JavaScript, without actually writing JavaScript-- Imba v1 is very close to this, but is no longer supported. I hope to be able to contribute to patching it up, and will of course check to see if any bugs I find in it are present in Imba v2, but am not really interested in upgrading to Imba v2 since I am most attracted to the grand ambition of V1. 

I will let you know If I can build an elegant way to interact with the dom/document without a shitshow of `:` and `.` (json and db adaptors I already am confident I can deal with)
