### ISSUE TITLE
Feature: Need a Unique Reference for individual Dom Elements (with Suggestions) & IDs don't update upon render

### ISSUE THREAD

**Issue by ericvida** [imba/imba#330]
If you look at the console on this playground

https://scrimba.com/c/cGmmbPhR

You will see that the class updates everytime you hit next, but the id doesn't. 

I'm not sure if that is a javascript native behavior, or an Imba bug. 

The reason for this, is to create a unique id for a dynamically created element/tag.
I have tried to do this myself in the past, and I think Imba could provide a better native solution for this. I mentioned a solution on my latest comment on issue #325, but I'll repeat it here, in case it makes more sense to have it here. 

### Solution example:

For example if did this:

`<div #book-{UID} UID>`

the element would be rendered with a unique id.

`<div #book-14353 data-14353>`  

This could possibly be used for scoped css as well, since each tag or element would have a Unique ID (UID) accessible, even if the tag is dynamically instantiated multiple times.

```imba
tag app-root
    <self UID>
        <h1> "Hello World"
   <css scoped> # scoped to app-root using UID
        h1 {color: purple}
```

**Comment by shishtpal** [comment]
Yes Dynamic ID is not updating even when data changes.
Why I need Dynamic ID?
* Because I am trying to create a wrapper for https://github.com/fengyuanchen/cropperjs
* So I need access to HTML DOM Element

But I have one suggestion, I has used Vue.js and in Vue there is a special tag `v-ref` which we can use inside tags, which keeps a reference to HTML DOM Element, that we can directly pass to other functions.
Can't we implement something like this in Imba2, because Imba2 is still being developed.
Thank You

**Comment by iamtirado** [comment]
@somebee 
I just took a look at [vue's ref](https://vuejs.org/v2/api/#ref), and it would be a wonderful feature in Imba, and I would agree that it's a great alternative to dynamically updating Id's or classes.

**Comment by iamtirado** [comment]
But I think a `uid` would be more flexible.

**Comment by shishtpal** [comment]
> But I think a `uid` would be more flexible.

why, `uid`?
`ref` means a reference to DOM Element. Isn't that correct?

**Comment by shishtpal** [comment]
> ```
> tag book-item
>   <self> this.ref
>   console.log this.ref.self # This would be book-#

In think we should use `this.refs.header`
```
tag app-root
  <self>
    <h1 ref="header">
    console.log this.refs.header

```
