### ISSUE TITLE
Feature: base style property

### ISSUE THREAD

**Issue by ericvida** [imba/imba#372]
It's a common practice to normalize browser styles, so maybe we can include a property for that.

Different individuals might be used to working with different popular base styles, so I thought we could support a few popular base styles with a `base: style` property syntax.

Here are a few popular base styles
Meyer's [reset.css](https://meyerweb.com/eric/tools/css/reset/) — `base: reset`
Necolas' [normalize.css](https://github.com/necolas/normalize.css/) — `base: normalize`
CSSTools' [sanitize.css](https://github.com/csstools/sanitize.css) — `base: sanitize`

### Usecase
```imba
css @root
    base: normalize
```

What do you think?

**Comment by somebee** [comment]
How to do normalization is a good question - it definitely makes sense for Imba to supply some sort of normalization, but it has to be opt-in. To illustrate the potential need to allow for different ones - you mention three popular ones, but we use tailwind preflight on the new imba.io :)

I also like the idea of being able to set it this way, since one could theoretically to resets only inside a specific part of your app.
