### ISSUE TITLE
certain css causes error in v129

### ISSUE THREAD

**Issue by trafnar** [imba/imba#524]
in imba alpha 129, if you make an app with the default imba template and replace the css at top of `client.imba` with this:
```
global css
	$mid-gray: #636363
```
you'll get this error

```
    location: {
      column: 27,
      file: 'node_modules/imba/bin/imba.imba.js',
      length: 0,
      line: 13282,
      lineText: '        errors: res.errors.map(function(_0) {\n' +
        '    at /Users/trafnar/Desktop/cssproblem/node_modules/imba/bin/imba.imba.js:13282:28\n' +
        '    at runMicrotasks (<anonymous>)',
      namespace: 'file'
    },
    notes: [ [Object] ],
    text: "[imba] Cannot read property 'map' of undefined"
  }
```

**Comment by andregoldstein** [comment]
I believe @somebee said that this is due to not having any selector at all. He said he may try and automate this but if not the correct syntax should be:

```
global css @root $mid-gray: #636363
```

See here https://discord.com/channels/682180555286380545/682180555286380726/820173503340871700

Will close for now as I don't really think this is a bug. Can create a feature request though to automated adding a root selector
