### ISSUE TITLE
Targeting es5

### ISSUE THREAD

**Issue by viveksjain** [imba/imba#586]
### Description

Hi, enjoying playing around with imba so far. However, for my current project I need es5 (possibly even lower) support. I see that imba uses esbuild, not sure if it's even configurable but anyways esbuild doesn't fully support es5. Is there any way to integrate babel (or equivalent, swc seems to be the new hotness) with imba?

**Comment by somebee** [comment]
Sadly, if you plan to use tags or any other fancy features of Imba it depends quite heavily on things like `Symbol` which isn't easily simulated shimmed in es5 or lower. Imba v1 was much more conservative re. using these new features but for v2 I decided pretty early on targeting es6 since adoption will only go one way and it allows us to implement a ton of things more efficiently.

**Comment by viveksjain** [comment]
That makes sense, thanks for clarifying/confirming! Based on quick googling it does seem like babel supports polyfill for Symbol, but it's totally reasonable if it's not a design goal to support older browsers and you don't want to spend time trying to get it to work. Will close this and keep imba in mind for future projects.
