### ISSUE TITLE
Falsey props are being converted to non-falsey strings

### ISSUE THREAD

**Issue by andregoldstein** [imba/imba#655]
Imba version: alpha 175

When trying to check for the presence/truthiness of a prop to conditionally affect layout, it appears Imba is converting falsey values to non-falsey strings.

https://scrimba.com/scrim/c8GP2ZsE

```
tag app-block
    prop title
    <self>
        if title
            <div> <h4> title
            <div> <slot>
        else
            <slot>

tag App
    
    <self>
        <app-block title="My title"> "Contents"
        <app-block> "Contents" # absent title prop gets converted to "undefined"
```
![Screenshot 2022-03-09 at 16 03 26](https://user-images.githubusercontent.com/7061578/157468577-445ac8fc-4f74-40e6-be94-aefb7d81dbdd.png)

**Comment by somebee** [comment]
Ah, this is an interesting bug. Since title is already an existing [IDL attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#content_versus_idl_attributes) , this breaks in a weird way. Imba always initializes all props to a default value or undefined. If you set someDomElement.title = undefined, it will actually convert to a string. So, if you either do `prop title = ''` or use a different property (which I would recommend, since title is automatically shown when hovering the whole element etc), this problem should go away. Still something we should handle differently I think.

**Comment by andregoldstein** [comment]
Ah, you know I never even considered it was due to using `title` as a property. Can totally work around this by using a different property name indeed.
