### ISSUE TITLE
Can't type decimals in input type number

### ISSUE THREAD

**Issue by andregoldstein** [imba/imba#701]
When attempting to type a decimal number into a _bound_ number input, adding a `.` character to start a decimal results in the input being cleared.

I think it's Imba trying to coerce the number tag by default (which I think it does?) and maybe hitting a NaN issue and defaulting the bound value back to ""?

See https://scrimba.com/scrim/cwGdZvtJ

Note: Non-bound inputs work fine and values can also be pasted

**Comment by somebee** [comment]
Added a basic fix now. Not completely satisfied with it, but would like to hear your thoughts about it. Now it will not update the bound value unless the number is valid. This makes sense in most cases, but if the number input says "4" and you backspace so that it is blank, the data value will still be 4, until another valid number is written. Should it rather go to 0? Or null?

**Comment by andregoldstein** [comment]
Thanks! It's really tricky isn't it? I think your solution could work really well, maybe `null` is a more logical choice as it's not so much a default as `0` would be and therefore more representative of the fact that it's sort of in a `non-selected` state?

**Comment by andregoldstein** [comment]
Was trying to see how other libs that use 2-way binding handle it - Svelte seems to use `null` I think

https://svelte.dev/tutorial/numeric-inputs
