### ISSUE TITLE
getting trouble to create imba app

### ISSUE THREAD

**Issue by 1196772405** [imba/imba#750]
### Description

PS D:\imbaProject> npx imba create my-app
√ Choose your template · Full Stack
✖ Something went wrong during creation
  Please report at https://github.com/imba/imba/issues

### Reproduction

1

### System Environment

```text
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 7.14 GB / 15.41 GB
  Binaries:
    Node: 16.17.1 - D:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```

**Comment by familyfriendlymikey** [comment]
Thanks for reporting. If you use tha Jamstack (Vite) template, does it work?

**Comment by peter-wasilko** [comment]
I have noticed that in the last two releases of imba, 223 and 224, if the version of vite-plugin-imba is set to 0.4.1 everything works; however, if I version bump the plugin up to the latest version at 0.10.0 the code seems to be bundled just fine, but something goes wrong at run time and all I get is a blank solid white window instead of the working app produced by the older plugin-version.

So the templates that use "latest" or "0.10.0" for the version won't work, whereas any that "^0.4.1" will, unless the pack-lock is set to "0.10.0".

**Comment by haikyuu** [comment]
But this issue is about windows. And unfortunately, none of the maintainers has a windows machine.

But I think the problem comes from trying to use git in windows environments.

It might be better to copy what Vite is doing https://github.com/vitejs/vite/blob/main/packages/create-vite/src/index.ts

**Comment by familyfriendlymikey** [comment]
@haikyuu I mentioned in #747 that I'd be willing to implement improvements to `imba create` likely based on how Vite does it. I just need approval since it probably involves rewriting most of the script.

**Comment by haikyuu** [comment]
Please go ahead. Not working in windows is a major bug

**Comment by jaymakes11** [comment]
I'm seeing a related issue (the same?) on Mac (Safari/webkit only). 

If replacing all of the code in `main.imba` with the following things work:

```imba
imba.mount <div> "hello world"
```

The error seems to be triggered when trying to output a `tag`.

**Comment by familyfriendlymikey** [comment]
New `create` has since been implemented, thanks :)
