### ISSUE TITLE
Amazing IMBA

### ISSUE THREAD

**Issue by ansarizafar** [imba/imba#91]
I have just found amazing IMBA today. I have not seen anything better than IMBA. I am surprised why development of such an amazing language is slow down since last few months and Why it is not popular.

**Comment by somebee** [comment]
Thank you for the kind words :) I agree, Imba is actually pretty great. Development has slowed lately, but only because we have been busy creating scrimba.com which is written in Imba, and will be an amazing resource for learning Imba (and other languages)! Expect to see more tutorials about Imba in the coming week. Up until now it has been very difficult to get started with. With improved documentation let's hope more people will find it and like it!

**Comment by ansarizafar** [comment]
Is there any road map available? Have you seen EVE [witheve.com](http://witheve.com) They are also developing an editor and a build-in database.

**Comment by ansarizafar** [comment]
Is this project dead?

**Comment by somebee** [comment]
Not at all, but we are currently working hard on [scrimba.com](https://scrimba.com) - which is fully built in Imba. Haven't had much time to devote to the language itself lately, but we want to get 1.0.0 out the door asap.

**Comment by cooldesigns** [comment]
Is scrimba open source? I think it must certainly be open source because of we need to see best practices of imba for using it in our projects.

**Comment by somebee** [comment]
We might open source it in the future, but it's not in our current plans. I definitely want to create some examples for best practices, but I'm still a little too swamped with work on scrimba :/

**Comment by scanf** [comment]
Imba is very much alive! The low activity thing is just a temporary issue, which will be fixed over time.

Don't see any bug reports in here so closing. Please open up new issues if I missed something in this thread :wink:

Thanks.
